# Site settings
title: "Billets d'un Devops Ruby, mais pas que..."
email: sfeuga@member.fsf.org
description: > # this means to ignore newlines until "baseurl:"
  Devops Ruby at [Accenture](http://www.accenture.com), former system administrator.  
  Specialized on GNU/Linux system.
  Member of the [Free Software Fundation](http://www.fsf.org/).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sfeuga.github.io" # the base hostname & protocol for your site
twitter_username: https://twitter.com/sfeuga
github_username:  https://github.com/sfeuga
linkedin_username: https://www.linkedin.com/in/sfeuga

# Build settings
markdown: kramdown

exclude:  ["README.md","Gemfile","Gemfile.lock","CNAME"]

encoding: utf-8
