# Site settings
title: "Billets d'un Devops Ruby, mais pas que..."
email: sfeuga@member.fsf.org
description: > # this means to ignore newlines until "baseurl:"
  Senior Devops Ruby at [Accenture](http://www.accenture.com) for the [World Economic Forum](https://www.weforum.org). Former system administrator, specialized on GNU/Linux system.

  Member of the [Free Software Fundation](http://www.fsf.org/).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sfeuga.github.io" # the base hostname & protocol for your site
twitter: https://twitter.com/sfeuga
github:  https://github.com/sfeuga
linkedin: https://www.linkedin.com/in/sfeuga

collections:
  list:
    output: true

# Build settings
markdown: kramdown
exclude:  ["README.md","Gemfile","Gemfile.lock","CNAME"]
encoding: utf-8
gems:
  - jekyll-feed
