# site settings
title: The Meaning of The Evil
email: sfeuga@member.fsf.org
author: Stéphane FEUGA

description: >- # this means to ignore newlines until "baseurl:"
  A place to talk about CG, Hardware, Software, Irix & SGI related stuff and much more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sfeuga.github.io" # the base hostname & protocol for your site

theme: minima

# social settings
github_username:   sfeuga
linkedin_username: sfeuga
twitter_username:  sfeuga

# build settings
markdown: kramdown
encoding: utf-8

plugins:
  - jekyll-feed

collections:
  hardware:
    output: true

# Exclude from processing.
exclude:
  - .gitignore
  - .gitlab-ci.yml
  - .jekyll-metadata
  - .ruby-version
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
